// Generated by Selenium IDE
Require('chromedriver');
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('batman sin colores', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('batman sin colores', async function() {
    await driver.get("http://localhost:3000/shows")
    await driver.manage().window().setRect(844, 606)
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).sendKeys("batman")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".btn")).click()
  })
})
